import {Typography} from "@material-ui/core";
import React from "react";

const vocabs = {
    'damage-assessment': 'Damage Assessment and reconstruction system',
    'baztab-project': 'BAZTAB Project',
    'humanitarian-protection': 'Humanitarian Protection and Community Rehabilitation in Kermanshah Province',
    'islamic-republic': 'Islamic Republic of Iran',
    'login': 'Login',
    'english': 'English',
    'persian': 'Persian',
    'sign-in': 'Sign in',
    'password': 'Password',
    'email-address': 'Email Address',
    'copyright': 'Copyright © ',
    'un-habitat': 'UN Habitat',
    'national-view': 'National View',
    'selected-province': 'Selected Province',
    'selected-county': 'Selected County',
    'selected-village': 'Selected Village',
    'flood-hazard-zone': 'Flood Hazard Zone',
    'seismic-hazard-zone': 'Seismic Hazard Zone',
    'stage-one': "Stage One",
    'stage-two': "Stage Two",
    'stage-three': "Stage Three",
    'stage-four': "Stage Four",
    'logout': "Log Out",
    'first-name': "First Name",
    'last-name': "Last Name",
    'user-name': "User Name",
    'user-role': "User Role",
    'email': "Email",
    'phone-number': "Phone Number",
    'users-table': "Users Table",
    'agent-name': "Agent Name",
    'assigned-subdivision': "Assigned Subdivision",
    'task-reporter': "Task Reporter",
    'tasks-table': "Tasks Table",
    'past-year-progress-by-month': "Past Year Progress by Month",
    'selected-user': 'Selected User',
    'tasks-form': 'Tasks Form',
    'users-form': 'Users Form',
    'cancel': 'Cancel',
    'save': 'Save',
    'confirm-password': 'Confirm Password',
    'agent': 'Agent',
    'admin': 'Admin',
    'dashboard': 'Dashboard',
    'home': 'Home',
    'users': 'Users',
    'tasks': 'Tasks',
    'my-tasks': 'My Tasks',
    'profile': 'Profile',
};

export const en = (key) => vocabs[key] || `unknown(${key})`;
