const vocabs = {
    'damage-assessment': 'Damage Assessment and reconstruction system',
    'baztab-project': 'BAZTAB Project',
    'humanitarian-protection': 'Humanitarian Protection and Community Rehabilitation in Kermanshah Province',
    'islamic-republic': 'Islamic Republic of Iran',
    'login': 'Login',
    'english': 'English',
    'persian': 'Persian',
    'sign-in': 'Sign in',
    'password': 'Password',
    'email-address': 'Email Address',
    'copyright': 'Copyright © ',
    'un-habitat': 'UN Habitat',
    'national-view': 'National View',
    'selected-province': 'Selected Province',
    'selected-county': 'Selected County',
    'selected-village': 'Selected Village',
    'flood-hazard-zone': 'Flood Hazard Zone',
    'seismic-hazard-zone': 'Seismic Hazard Zone',
    'stage-one': "Stage One",
    'stage-two': "Stage Two",
    'stage-three': "Stage Three",
    'stage-four': "Stage Four",
    'logout': "Log Out",
    'first-name': "First Name",
    'last-name': "Last Name",
    'user-name': "User Name",
    'user-role': "User Role",
    'email': "Email",
    'phone-number': "Phone Number",
    'users-table': "Users Table",
    'agent-name': "Agent Name",
    'assigned-subdivision': "Assigned Subdivision",
    'task-reporter': "Task Reporter",
    'tasks-table': "Tasks Table",
    'past-year-progress-by-month': "Past Year Progress by Month",
    'selected-user': 'Selected User',
    'tasks-form': 'Tasks Form',
    'users-form': 'Users Form',
    'cancel': 'Cancel',
    'save': 'Save',
    'confirm-password': 'Confirm Password',
    'agent': 'Agent',
    'admin': 'Admin',
    'dashboard': 'Dashboard',
    'home': 'Home',
    'users': 'Define Users',
    'tasks': 'Define Tasks',
    'my-tasks': 'My Tasks',
    'profile': 'Profile',
    'my-tasks-table': 'My Tasks Table',
    'my-dashboard': 'My Dashboard',
    'list-of-assessed-units': 'List of assessed units',
    'list-of-issue-to-bank': ' List of issue to bank',
    'list-of-appeals-objections': 'List of appeals / objections',
    'assigned-units': 'Assigned Units: ',
    'damage-assessments': 'Damage Assessments',
    'issue-letter': 'Issue Letters',
    'appeals-objections': 'Appeals / Objections',
    'referrence_code': 'Reference Code',
    'subdivision': 'Subdivision',
    'incident': 'Incident',
    'damage_type': 'Damage Type',
    'stage_number': 'Stage Number',
    'is_wall_damaged': 'Is Wall Damaged',
    'view-objection': 'View Objection',
    'download-letter': 'Download Letter',
    'objection-review': 'Objection Review',
    'objection-text': 'Objection Text',
    'stage': 'Stage',
    'yes': 'Yes',
    'no': 'No',
    'export-letter': 'Issue Letter',
    'preliminary': 'Preliminary',
    'incident-name': 'Incident Name',
    'coordinate-x': 'Incident X Coordinate',
    'coordinate-y': 'Incident Y Coordinate',
    'show-coordinates': 'Show Coordinates',
    'confirm-incident': 'Confirm Incident',
    'loading-dashboard': 'Loading Dashboard... ',
    'user-expired': 'Your username or password has been expired!',
    'unauthorized': 'Invalid username or password',
    'auth-error': 'Authentication Error',
    'survey-table': 'Survey Table',
    'category-table': 'Category Table',
    'question-table': 'Question Table',
    'stage-one-name': 'Damage Assessment',
    'stage-two-name': 'Foundation & Structure',
    'stage-three-name': 'Walls & Ceiling',
    'stage-four-name': 'Finishing',
    'survey-forms': 'Survey Forms',
    'categories': 'Categories',
    'questions': 'Questions',
    'loading-data': 'Loading Data'
};

export const en = (key) => vocabs[key] || `unknown(${key})`;
